# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-17 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, max_length=1000, upload_to='avatar', verbose_name='avatar')),
                ('id_telegram', models.BigIntegerField(blank=True, default=0, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('birthday', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата рождения')),
                ('itn', models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=12, null=True, validators=[users.validators.validate_contact_phone_numeric, users.validators.validate_contact_phone_length], verbose_name='Номер телефона')),
                ('registration_area_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Реєстрації')),
                ('registration_raion_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Реєстрації')),
                ('registration_city_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Реєстрації')),
                ('registration_street_ur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Реєстрації')),
                ('House_number_ur', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Реєстрації')),
                ('apartment_number_ur', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Реєстрації')),
                ('registration_area_fiz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Проживання')),
                ('registration_raion_fiz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Проживання')),
                ('registration_city_fiz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Проживання')),
                ('registration_street_fiz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Проживання')),
                ('House_number_fiz', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Проживання')),
                ('apartment_number_fiz', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Проживання')),
                ('passport_series', models.CharField(blank=True, max_length=16, null=True, validators=[users.validators.validate_passport_series], verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=32, verbose_name='Номер паспорта')),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспорт кем Видано')),
                ('date_of_issue', models.DateField(blank=True, null=True, verbose_name='Паспорт Дата Видачі')),
                ('mailing_list', models.BooleanField(default=True, verbose_name='Участь в розсилках')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
