# Generated by Django 2.1.5 on 2019-06-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.FileField(blank=True, max_length=1000, upload_to='avatar', verbose_name='avatar'),
        ),
    ]
