# Generated by Django 2.1.5 on 2019-06-11 08:33

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190607_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='House_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='House_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='apartment_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='apartment_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='base_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID бази'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cod_number_phone1',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 1'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cod_number_phone2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 2'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cod_number_phone3',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 3'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cod_number_phone4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 4'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cod_number_phone5',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 5'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cod_number_phone_work',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код телефона рабочий'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[users.validators.validate_contact_phone_numeric, users.validators.validate_contact_phone_length], verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Паспорт Дата Видачі'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='family_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сімейний Дохід'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дохід'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='issued_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспорт Ким Видано'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='itn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='mailing_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Участь в розсилках'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='name_base',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва Бази'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='name_project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва проекту'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_Telegram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Telegram'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_Viber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Viber'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_WhatsApp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер WhatsApp'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 1'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 2'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_phone3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 3'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_phone4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 4'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_phone5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 5'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_phone_work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона рабочий'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='other_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Інший Дохід'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='passport_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='passport_series',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[users.validators.validate_passport_series], verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце Роботи'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Посада'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID проекту'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_area_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_area_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_city_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_city_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_raion_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_raion_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_street_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_street_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='status_Viber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус Viber'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='total_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Загальний Дохід'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='birthday',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата рождения'),
        ),
    ]
