# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-15 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profileuser_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[users.validators.validate_contact_phone_numeric, users.validators.validate_contact_phone_length])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='House_number_fiz',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='day_in_system',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='house_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Дома Проживания'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='vicidial_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер Vicidial'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='apartment_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартиры Проживания'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='registration_area_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Проживания'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='registration_city_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город Проживания'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='registration_raion_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Проживания'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='registration_street_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улия Проживания'),
        ),
    ]
