# Generated by Django 2.1.5 on 2019-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190611_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='House_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='House_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='apartment_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='apartment_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_area_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_area_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_city_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_city_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_raion_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_raion_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Реєстрації'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_street_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Проживання'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='registration_street_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Реєстрації'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='issued_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспорт кем Видано'),
        ),
    ]
