# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191115_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='', max_length=12, validators=[users.validators.validate_contact_phone_numeric, users.validators.validate_contact_phone_length]),
            preserve_default=False,
        ),
    ]
