# Generated by Django 2.1.5 on 2019-06-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190611_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='name_base',
        ),
    ]
