# Generated by Django 2.1.5 on 2019-06-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190611_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='id_telegramm',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='name_base',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='id_telegram',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
