# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-17 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vybor', models.BooleanField(default=False)),
                ('number_phone1', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 1')),
                ('cod_number_phone1', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 1')),
                ('number_phone2', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 2')),
                ('cod_number_phone2', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 2')),
                ('number_phone3', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 3')),
                ('cod_number_phone3', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 3')),
                ('number_phone4', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 4')),
                ('cod_number_phone4', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 4')),
                ('number_phone5', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 5')),
                ('cod_number_phone5', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 5')),
                ('number_Viber', models.CharField(blank=True, max_length=30, verbose_name='Номер Viber')),
                ('number_WhatsApp', models.CharField(blank=True, max_length=30, verbose_name='Номер WhatsApp')),
                ('number_Telegram', models.CharField(blank=True, max_length=30, verbose_name='Номер Telegram')),
                ('status_Viber', models.CharField(blank=True, max_length=255, verbose_name='Статус Viber')),
                ('place_of_work', models.CharField(blank=True, max_length=255, verbose_name='Місце Роботи')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Посада')),
                ('number_phone_work', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона рабочий')),
                ('cod_number_phone_work', models.CharField(blank=True, max_length=10, verbose_name='Код телефона рабочий')),
                ('income', models.IntegerField(blank=True, null=True, verbose_name='Дохід')),
                ('other_income', models.IntegerField(blank=True, null=True, verbose_name='Інший Дохід')),
                ('family_income', models.IntegerField(blank=True, null=True, verbose_name='Сімейний Дохід')),
                ('total_income', models.IntegerField(blank=True, null=True, verbose_name='Загальний Дохід')),
                ('name_base', models.CharField(blank=True, max_length=255, verbose_name='Назва Бази')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='Примітка')),
                ('base_id', models.CharField(blank=True, max_length=255, verbose_name='ID бази')),
                ('name_project', models.CharField(blank=True, max_length=255, verbose_name='Назва проекту')),
                ('project_id', models.CharField(blank=True, max_length=255, verbose_name='ID проекту')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_double', models.BooleanField(default=False, verbose_name='Дубль?')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'permissions': [('view_bid_double', 'Может видеть дубликаты')],
                'verbose_name': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='BidImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone1', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 1')),
                ('cod_number_phone1', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 1')),
                ('number_phone2', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 2')),
                ('cod_number_phone2', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 2')),
                ('number_phone3', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 3')),
                ('cod_number_phone3', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 3')),
                ('number_phone4', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 4')),
                ('cod_number_phone4', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 4')),
                ('number_phone5', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона 5')),
                ('cod_number_phone5', models.CharField(blank=True, max_length=4, verbose_name='Код телефона 5')),
                ('number_Viber', models.CharField(blank=True, max_length=30, verbose_name='Номер Viber')),
                ('number_WhatsApp', models.CharField(blank=True, max_length=30, verbose_name='Номер WhatsApp')),
                ('number_Telegram', models.CharField(blank=True, max_length=30, verbose_name='Номер Telegram')),
                ('status_Viber', models.CharField(blank=True, max_length=255, verbose_name='Статус Viber')),
                ('place_of_work', models.CharField(blank=True, max_length=255, verbose_name='Місце Роботи')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Посада')),
                ('number_phone_work', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона рабочий')),
                ('cod_number_phone_work', models.CharField(blank=True, max_length=10, verbose_name='Код телефона рабочий')),
                ('income', models.IntegerField(blank=True, null=True, verbose_name='Дохід')),
                ('other_income', models.IntegerField(blank=True, null=True, verbose_name='Інший Дохід')),
                ('family_income', models.IntegerField(blank=True, null=True, verbose_name='Сімейний Дохід')),
                ('total_income', models.IntegerField(blank=True, null=True, verbose_name='Загальний Дохід')),
                ('name_base', models.CharField(blank=True, max_length=255, verbose_name='Назва Бази')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='Примітка')),
                ('base_id', models.CharField(blank=True, max_length=255, verbose_name='ID бази')),
                ('name_project', models.CharField(blank=True, max_length=255, verbose_name='Назва проекту')),
                ('project_id', models.CharField(blank=True, max_length=255, verbose_name='ID проекту')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Город')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name_plural': 'Импорт заявок',
                'verbose_name': 'Импорт завки',
            },
        ),
        migrations.CreateModel(
            name='BidStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Имя/Название статуса')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код статуса')),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1, verbose_name='Уровень вложения')),
                ('group', models.ManyToManyField(to='auth.Group', verbose_name='Группа')),
                ('parent_level_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bids.BidStatus', verbose_name='Родительский уровень статуса')),
            ],
            options={
                'verbose_name_plural': 'Статусы заявок',
                'verbose_name': 'Статус заявки',
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid', verbose_name='Заявка')),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.BidStatus', verbose_name='Имя статуса')),
                ('user_who_edit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь изменивший этот статус')),
            ],
            options={
                'verbose_name_plural': 'История статусов',
                'verbose_name': 'История статусов',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.BidStatus', verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user_who_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bids', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь изменивший эту заявку'),
        ),
    ]
