# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='appointment_dt',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='for_skybank',
        ),
    ]
