# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20190426_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='crm_status',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='site_bid_id',
        ),
        migrations.RemoveField(
            model_name='biddouble',
            name='appointment_dt',
        ),
        migrations.RemoveField(
            model_name='biddouble',
            name='crm_status',
        ),
        migrations.RemoveField(
            model_name='biddouble',
            name='for_skybank',
        ),
        migrations.RemoveField(
            model_name='biddouble',
            name='site_bid_id',
        ),
        migrations.RemoveField(
            model_name='bidimport',
            name='crm_status',
        ),
        migrations.RemoveField(
            model_name='bidimport',
            name='for_skybank',
        ),
        migrations.RemoveField(
            model_name='bidimport',
            name='site_bid_id',
        ),
    ]
