# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-10 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '0009_auto_20190508_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidimport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь изменивший эту заявку'),
        ),
    ]
