# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-11 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0010_bidimport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidimport',
            name='user',
        ),
    ]
