# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-24 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0012_bid_vybor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='vybor',
            field=models.IntegerField(blank=True, max_length=1),
        ),
    ]
