# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-31 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0014_auto_20190524_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='vybor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
