# Generated by Django 2.1.5 on 2019-06-11 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0016_auto_20190611_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidstatus',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=1, max_length=1, verbose_name='Уровень вложения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidstatus',
            name='parent_level_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bids.BidStatus', verbose_name='Высший уровень статуса'),
        ),
    ]
