# Generated by Django 2.1.5 on 2019-06-11 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '0018_auto_20190611_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='user_who_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bids', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь изменивший эту заявку'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='user_who_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_double_bids', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь изменивший эту заявку'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biddouble',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
