# Generated by Django 2.1.5 on 2019-06-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0019_auto_20190611_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='credit_sum',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='lead_id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='vybor',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='webmaster_id',
        ),
        migrations.RemoveField(
            model_name='biddouble',
            name='groupid',
        ),
        migrations.RemoveField(
            model_name='biddouble',
            name='lead_id',
        ),
        migrations.RemoveField(
            model_name='bidimport',
            name='groupid',
        ),
        migrations.AddField(
            model_name='bid',
            name='House_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Проживання'),
        ),
        migrations.AddField(
            model_name='bid',
            name='House_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Реєстрації'),
        ),
        migrations.AddField(
            model_name='bid',
            name='apartment_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Проживання'),
        ),
        migrations.AddField(
            model_name='bid',
            name='apartment_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Реєстрації'),
        ),
        migrations.AddField(
            model_name='bid',
            name='base_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID бази'),
        ),
        migrations.AddField(
            model_name='bid',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='bid',
            name='cod_number_phone1',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 1'),
        ),
        migrations.AddField(
            model_name='bid',
            name='cod_number_phone2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 2'),
        ),
        migrations.AddField(
            model_name='bid',
            name='cod_number_phone3',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 3'),
        ),
        migrations.AddField(
            model_name='bid',
            name='cod_number_phone4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 4'),
        ),
        migrations.AddField(
            model_name='bid',
            name='cod_number_phone5',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 5'),
        ),
        migrations.AddField(
            model_name='bid',
            name='cod_number_phone_work',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код телефона рабочий'),
        ),
        migrations.AddField(
            model_name='bid',
            name='family_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сімейний Дохід'),
        ),
        migrations.AddField(
            model_name='bid',
            name='income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дохід'),
        ),
        migrations.AddField(
            model_name='bid',
            name='name_project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва проекту'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_Telegram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Telegram'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_Viber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Viber'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_WhatsApp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер WhatsApp'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 1'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 2'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_phone3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 3'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_phone4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 4'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_phone5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 5'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_phone_work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона рабочий'),
        ),
        migrations.AddField(
            model_name='bid',
            name='other_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Інший Дохід'),
        ),
        migrations.AddField(
            model_name='bid',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце Роботи'),
        ),
        migrations.AddField(
            model_name='bid',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Посада'),
        ),
        migrations.AddField(
            model_name='bid',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID проекту'),
        ),
        migrations.AddField(
            model_name='bid',
            name='registration_area_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Проживання'),
        ),
        migrations.AddField(
            model_name='bid',
            name='registration_area_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Реєстрації'),
        ),
        migrations.AddField(
            model_name='bid',
            name='registration_city_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Проживання'),
        ),
        migrations.AddField(
            model_name='bid',
            name='registration_city_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Реєстрації'),
        ),
        migrations.AddField(
            model_name='bid',
            name='registration_raion_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Проживання'),
        ),
        migrations.AddField(
            model_name='bid',
            name='registration_raion_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Реєстрації'),
        ),
        migrations.AddField(
            model_name='bid',
            name='registration_street_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Проживання'),
        ),
        migrations.AddField(
            model_name='bid',
            name='registration_street_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Реєстрації'),
        ),
        migrations.AddField(
            model_name='bid',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка'),
        ),
        migrations.AddField(
            model_name='bid',
            name='status_Viber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус Viber'),
        ),
        migrations.AddField(
            model_name='bid',
            name='total_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Загальний Дохід'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='House_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Проживання'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='House_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Реєстрації'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='apartment_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Проживання'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='apartment_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Реєстрації'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='base_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID бази'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='cod_number_phone1',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 1'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='cod_number_phone2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 2'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='cod_number_phone3',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 3'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='cod_number_phone4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 4'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='cod_number_phone5',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 5'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='cod_number_phone_work',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код телефона рабочий'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='family_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сімейний Дохід'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дохід'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='name_project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва проекту'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='number_Telegram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Telegram'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='number_Viber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Viber'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='number_WhatsApp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер WhatsApp'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='number_phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 1'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='number_phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 2'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='number_phone3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 3'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='number_phone4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 4'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='number_phone5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 5'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='number_phone_work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона рабочий'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='other_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Інший Дохід'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце Роботи'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Посада'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID проекту'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='registration_area_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Проживання'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='registration_area_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Реєстрації'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='registration_city_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Проживання'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='registration_city_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Реєстрації'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='registration_raion_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Проживання'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='registration_raion_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Реєстрації'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='registration_street_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Проживання'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='registration_street_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Реєстрації'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='status_Viber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус Viber'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='total_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Загальний Дохід'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='House_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Проживання'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='House_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Будинку Реєстрації'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='apartment_number_fiz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Проживання'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='apartment_number_ur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Квартири Реєстрації'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='base_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID бази'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='cod_number_phone1',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 1'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='cod_number_phone2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 2'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='cod_number_phone3',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 3'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='cod_number_phone4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 4'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='cod_number_phone5',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона 5'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='cod_number_phone_work',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код телефона рабочий'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='family_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сімейний Дохід'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дохід'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='name_project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва проекту'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='number_Telegram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Telegram'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='number_Viber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Viber'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='number_WhatsApp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер WhatsApp'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='number_phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 1'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='number_phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 2'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='number_phone3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 3'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='number_phone4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 4'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='number_phone5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона 5'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='number_phone_work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона рабочий'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='other_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Інший Дохід'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце Роботи'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Посада'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID проекту'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='registration_area_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Проживання'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='registration_area_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область Реєстрації'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='registration_city_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Проживання'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='registration_city_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто Реєстрації'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='registration_raion_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Проживання'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='registration_raion_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район Реєстрації'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='registration_street_fiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Проживання'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='registration_street_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця Реєстрації'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='status_Viber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус Viber'),
        ),
        migrations.AddField(
            model_name='bidimport',
            name='total_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Загальний Дохід'),
        ),
    ]
