# Generated by Django 2.1.5 on 2019-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0021_auto_20190611_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='mailing_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Участь в розсилках'),
        ),
        migrations.AddField(
            model_name='bid',
            name='name_base',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва Бази'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='mailing_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Участь в розсилках'),
        ),
        migrations.AddField(
            model_name='biddouble',
            name='name_base',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва Бази'),
        ),
    ]
