# Generated by Django 2.1.5 on 2019-06-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0022_auto_20190611_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidimport',
            options={'verbose_name': 'Импорт завки', 'verbose_name_plural': 'Импорт заявок'},
        ),
    ]
