# Generated by Django 2.1.5 on 2019-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0023_auto_20190611_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='vybor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
