# Generated by Django 2.1.5 on 2019-06-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0024_bid_vybor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='mailing_list',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='biddouble',
            name='mailing_list',
        ),
        migrations.RemoveField(
            model_name='bidimport',
            name='mailing_list',
        ),
    ]
