# Generated by Django 2.1.5 on 2019-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('bids', '0025_auto_20190612_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidstatus',
            name='group',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Группа'),
        ),
    ]
