# Generated by Django 2.1.5 on 2019-06-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0026_bidstatus_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biddouble',
            options={'permissions': [('see_double_bids', 'Can see page with double bids')], 'verbose_name': 'Заявка (Дубль)', 'verbose_name_plural': 'Заявки (Дубли)'},
        ),
        migrations.AlterModelOptions(
            name='bidimport',
            options={'permissions': [('see_import_bids', 'Can see page with import bids')], 'verbose_name': 'Импорт завки', 'verbose_name_plural': 'Импорт заявок'},
        ),
        migrations.RemoveField(
            model_name='bidimport',
            name='groupid',
        ),
    ]
