# Generated by Django 2.1.5 on 2019-06-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0027_auto_20190613_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biddouble',
            options={'permissions': [('see_double_bids', 'Доступ к дублям заявок')], 'verbose_name': 'Заявка (Дубль)', 'verbose_name_plural': 'Заявки (Дубли)'},
        ),
        migrations.AlterModelOptions(
            name='bidimport',
            options={'permissions': [('see_import_bids', 'Доступ к импорту заявок')], 'verbose_name': 'Импорт завки', 'verbose_name_plural': 'Импорт заявок'},
        ),
    ]
