# Generated by Django 2.1.5 on 2019-06-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0028_auto_20190613_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('big', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid', verbose_name='Заявка')),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.BidStatus', verbose_name='Имя статуса')),
            ],
            options={
                'verbose_name': 'История статусов',
                'verbose_name_plural': 'История статусов',
            },
        ),
        migrations.AlterModelOptions(
            name='biddouble',
            options={'verbose_name': 'Заявка (Дубль)', 'verbose_name_plural': 'Заявки (Дубли)'},
        ),
        migrations.AlterModelOptions(
            name='bidimport',
            options={'verbose_name': 'Импорт завки', 'verbose_name_plural': 'Импорт заявок'},
        ),
    ]
