# Generated by Django 2.1.5 on 2019-06-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0030_auto_20190614_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddouble',
            name='status',
        ),
        migrations.RemoveField(
            model_name='biddouble',
            name='user',
        ),
        migrations.RemoveField(
            model_name='biddouble',
            name='user_who_edit',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='vybor',
        ),
        migrations.AddField(
            model_name='bid',
            name='is_double',
            field=models.BooleanField(default=False, verbose_name='Дубль?'),
        ),
        migrations.DeleteModel(
            name='BidDouble',
        ),
    ]
