# Generated by Django 2.1.5 on 2019-06-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0032_bid_vybor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'permissions': [('view_bid_double', 'Может видеть дубликаты')], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
    ]
