# Generated by Django 2.1.5 on 2019-06-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0033_auto_20190618_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statushistory',
            old_name='big',
            new_name='bid',
        ),
    ]
