# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0035_statushistory_user_who_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='base_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID бази'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='cod_number_phone1',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='cod_number_phone2',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='cod_number_phone3',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='cod_number_phone4',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='cod_number_phone5',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='cod_number_phone_work',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Код телефона рабочий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='name_project',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Назва проекту'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_Telegram',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Номер Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_Viber',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Номер Viber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_WhatsApp',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Номер WhatsApp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_phone1',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_phone2',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_phone3',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_phone4',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_phone5',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_phone_work',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона рабочий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='place_of_work',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Місце Роботи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='project_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID проекту'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Примітка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='status_Viber',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Статус Viber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='base_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID бази'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='cod_number_phone1',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='cod_number_phone2',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='cod_number_phone3',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='cod_number_phone4',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='cod_number_phone5',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Код телефона 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='cod_number_phone_work',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Код телефона рабочий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='name_base',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Назва Бази'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='name_project',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Назва проекту'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='number_Telegram',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Номер Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='number_Viber',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Номер Viber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='number_WhatsApp',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Номер WhatsApp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='number_phone1',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='number_phone2',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='number_phone3',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='number_phone4',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='number_phone5',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='number_phone_work',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона рабочий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='place_of_work',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Місце Роботи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Посада'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='project_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID проекту'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Примітка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidimport',
            name='status_Viber',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Статус Viber'),
            preserve_default=False,
        ),
    ]
