# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0036_auto_20190715_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Посада'),
            preserve_default=False,
        ),
    ]
